### ISSUE TITLE
Maven dependency in IntelliJ disabling Run

### ISSUE THREAD

**Issue by splicymusic** [Petersoj/alpaca-java#105]
I'm importing the alpaca-java with Maven in IntelliJ.  Very oddly this appears to disable running my app. The green play buttons and menu items for running are all there but using them does... nothing. Commenting out the alpaca-java dependency and restarting IntelliJ allows running. (Simply re-importing all maven dependencies does not do the trick).

Has anyone else experienced this?

I've seen this kind of issue pop up a few times in reference to Gradle:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000045539-RUN-simply-stopped-working-for-one-single-project-which-previously-worked-fine-no-changes-to-configuration-

Could the issues be related?

IntelliJ 2017.3 Ultimate Edition.

**Comment by Petersoj** [comment]
I use Intellij, but I do not use the built in build tool, but instead use the "Gradle" tab or Gradle from the command line. First, I would recommend you update Intellij to the latest version. The version you're using is quite outdated (the latest version is 2021.2). Second, have you tried using Maven from the command line to confirm that your `pom.xml` configuration is working? For example: `mvn clean build run`?

**Comment by splicymusic** [comment]
After updating IntelliJ the issue is resolved.  Thanks for the help with this issue!
