### ISSUE TITLE
Unsupported account status enum value

### ISSUE THREAD

**Issue by Kurru** [Petersoj/alpaca-java#110]
I observe an unsupported enum `status` from the account API during the account signup flow. 

`ACTION_REQUIRED`

This status value is reported as null by the current java API. 

Can this enum value be added to alpaca-java? This would [perhaps be added here](https://github.com/Petersoj/alpaca-java/blob/master/schema_json/endpoint/account/enums/account_status.json)? 

I found some reference to this in the [broker api documentation](https://alpaca.markets/docs/broker/api-references/accounts/accounts/#account-status), but observed this in the oauth v2 apis by manually sending the rpc using restman

Sent #111 as attempt to resolve

**Comment by Petersoj** [comment]
Patched in release [`8.3.3`](https://github.com/Petersoj/alpaca-java/releases/tag/8.3.3).
