### ISSUE TITLE
Need support for broker-api URL 

### ISSUE THREAD

**Issue by manojbhi23** [Petersoj/alpaca-java#112]
Currently AlpacaAPI constructor is supporting only api and paper-api URLs. For sandbox testing, it should support broker-api subdoamin as well

 switch (endpointAPIType) {
            case LIVE:
                brokerHostSubdomain = "api";
                break;
            case PAPER:
                brokerHostSubdomain = "paper-api";
                break;
  _**case SANDBOX:
                brokerHostSubdomain = "broker-api";
                break;**_
            default:
                throw new UnsupportedOperationException();
        }
this will help with below environment
https://broker-api.sandbox.alpaca.markets/v1/accounts

Thanks!

**Comment by Petersoj** [comment]
Sorry for the late response. I will look into Broker API support soon.

**Comment by Petersoj** [comment]
Broker API is now implemented in [`10.0.0`](https://github.com/Petersoj/alpaca-java/releases/tag/10.0.0).
