### ISSUE TITLE
TradeUpdateMessage (trade_upates) misses few fields

### ISSUE THREAD

**Issue by selivonchik** [Petersoj/alpaca-java#115]
According to Alpaca docs (https://alpaca.markets/docs/broker/api-references/events/#response-2) Trade Update events contains few more fields that are currently missed in TradeUpdateMessage:
![image](https://user-images.githubusercontent.com/4846161/150016055-3e5b0e3b-e45b-4094-9a49-b252266a450a.png)
To simplify events correlation exposing at least "account_id" and "event_id" might be very useful. Thanks.

**Comment by Petersoj** [comment]
Those fields are sent on the websocket stream for the Broker API, which isn't currently supported by this library at the moment (only single-user endpoints that use API keys are supported by this library). I'll look into supporting the Broker API at some point in the future.

**Comment by selivonchik** [comment]
Thank you

**Comment by Petersoj** [comment]
Broker API is now implemented in [`10.0.0`](https://github.com/Petersoj/alpaca-java/releases/tag/10.0.0).
