### ISSUE TITLE
OrdersEndpoint.requestLimitOrder() takes only Integer as quantity, should take Double

### ISSUE THREAD

**Issue by jessethouin** [Petersoj/alpaca-java#120]
Since OrdersEndpoint.requestLimitOrder() is a wrapper for OrdersEndpoint.requestOrder(), the type of "quantity" fields should match. For example, I should be able to submit a limit order for .075 BTCUSD, but am currently stuck with only whole numbers.

**Comment by Petersoj** [comment]
Fixed by PR #121.
