### ISSUE TITLE
Update enum value  for FTX in Exchange

### ISSUE THREAD

**Issue by TonyMaganga** [Petersoj/alpaca-java#124]
The enum value for FTX in net.jacobpeterson.alpaca.model.endpoint.marketdata.crypto.common.enums.Exchange should be changed to "FXTU" to match the [Crypto Pricing API ](https://alpaca.markets/docs/api-references/market-data-api/crypto-pricing-data/). 

`package net.jacobpeterson.alpaca.model.endpoint.marketdata.crypto.common.enums;

import com.google.gson.annotations.SerializedName;
import java.util.HashMap;
import java.util.Map;

public enum Exchange {
    @SerializedName("ERSX")
    ERISX("ERSX"),
    @SerializedName("FTX")
    FTX("FTX"),`

Currently an exception is thrown when getting trades

`net.jacobpeterson.alpaca.rest.AlpacaClientException: Status Code: 422, Status Message: "Unprocessable Entity", API Response Code: 42210000, API Response Message: "invalid exchange: FTX"
	at net.jacobpeterson.alpaca.rest.AlpacaClient.request(AlpacaClient.java:207)
	at net.jacobpeterson.alpaca.rest.AlpacaClient.requestJSON(AlpacaClient.java:162)
	at net.jacobpeterson.alpaca.rest.AlpacaClient.requestObject(AlpacaClient.java:140)
	at net.jacobpeterson.alpaca.rest.AlpacaClient.requestObject(AlpacaClient.java:122)
	at net.jacobpeterson.alpaca.rest.endpoint.marketdata.crypto.CryptoMarketDataEndpoint.getLatestTrade(CryptoMarketDataEndpoint.java:122)`

**Comment by Petersoj** [comment]
@TonyMaganga thanks for reporting this. I'll fix this in a release sometime next week.

**Comment by TonyMaganga** [comment]
@Petersoj just want to remind you of this bug. Please look into it

**Comment by Petersoj** [comment]
@TonyMaganga thanks for the follow up! I'll issue a patch release later today.

**Comment by Petersoj** [comment]
Fixed in [`9.1.2`](https://github.com/Petersoj/alpaca-java/releases/tag/9.1.2).

**Comment by TonyMaganga** [comment]
Thanks. I have tested it and works fine
