### ISSUE TITLE
Position Object is missing qty_available

### ISSUE THREAD

**Issue by dsgraham81** [Petersoj/alpaca-java#131]
It looks like the Position object is not parsing or exposing qty_available.

https://alpaca.markets/docs/api-references/trading-api/positions/#example

<html>
<body>

qty_available | string<int> | Total number of shares available minus open orders
-- | -- | --

</body>
</html>

This would be useful for what I am working on as I might have multiple orders on a security and don't want to put in a sell if I don't have enough for all of them to clear

**Comment by Petersoj** [comment]
Fixed in #132.
