### ISSUE TITLE
Compliatoion error in StreamingWebsocket.java and MarketDataWebsocket.java

### ISSUE THREAD

**Issue by modi1973** [Petersoj/alpaca-java#135]
It is giving error in the following line:
Arrays.stream(marketDataMessageTypes)
                .filter(not(SUBSCRIBABLE_MARKET_DATA_MESSAGE_TYPES::contains))
                .forEach(listenedMarketDataMessageTypes::add);

Compilation error:
The method filter(Predicate<? super StreamingMessageType>) in the type Stream<StreamingMessageType> is not applicable for the arguments (Predicate<Object>)

**Comment by Petersoj** [comment]
Are you trying to build the `alpaca-java` project on your machine or is this in your own project with an `alpaca-java` dependency? If the former, maybe try running the following command: `./gradlew clean generatePOJOs build`.

**Comment by Petersoj** [comment]
Stale issue so closing. Re-open as needed.
