### ISSUE TITLE
Fractional share orders must be Day orders

### ISSUE THREAD

**Issue by jc-gomes** [Petersoj/alpaca-java#140]
Right now when ordering fractional shares, the OrdersEndpoint (requestFractionalMarketOrder function) executes with a OrderTimeForce.GOOD_UNTIL_CANCELLED, this fails with status code 422 and response message specifying all fractional orders must be DAY orders. This will need to be fixed so that the order executes as a DAY order.

**Comment by Petersoj** [comment]
Should be fixed in [`10.0.0`](https://github.com/Petersoj/alpaca-java/releases/tag/10.0.0). Re-open if not.
