### ISSUE TITLE
Status Code: 422, Status Message: “Unprocessable Entity”, API Response Code: 40010001, API Response Message: “us_equity orders not allowed for account”

### ISSUE THREAD

**Issue by Andys52621** [Petersoj/alpaca-java#147]
Hi Jacob,

I got this error couple of times today in submitting a market buy order on the RIVIAN, which is a US equity.

Status Code: 422, Status Message: “Unprocessable Entity”, API Response Code: 40010001, API Response Message: “us_equity orders not allowed for account”

Do you know what caused this error ? Same account was perfectly working fine yesterday.  Had no issues.

thanks,
Andy

**Comment by Petersoj** [comment]
Should be fixed in [`10.0.0`](https://github.com/Petersoj/alpaca-java/releases/tag/10.0.0). Re-open if not.
