### ISSUE TITLE
Options API

### ISSUE THREAD

**Issue by dsgraham81** [Petersoj/alpaca-java#149]
We should make the changes necessary to handle the upcoming Options API that is in Beta.

https://docs.alpaca.markets/docs/options-trading

**Comment by dsgraham81** [comment]
I might be able to take a crack at this, but not sure how much time I have, so if others wanted to go for it, go ahead. Just wanted to get this on the radar.

**Comment by Petersoj** [comment]
It's on my to-do list 👍

**Comment by Petersoj** [comment]
Implemented in [`10.0.0`](https://github.com/Petersoj/alpaca-java/releases/tag/10.0.0).
