### ISSUE TITLE
StreamSocket issue

### ISSUE THREAD

**Issue by louisphilippe2** [Petersoj/alpaca-java#62]
Hi,

Perhaps this is not a software issue but i swear i cannot see how i could add a stream listener for watching the price of stocks. I know it's possible to do it since it's documented on the official API but could not find how here. Is it even implemented? 

Thank you

**Comment by mainstringargs** [comment]
Have you looked at the addPolygonStreamListener in [PolygonAPI](https://javadoc.io/doc/io.github.mainstringargs/alpaca-java/latest/io/github/mainstringargs/polygon/PolygonAPI.html)?  Is that what you're looking for or do you mean something else?

**Comment by louisphilippe2** [comment]
Hi,

I am reffering to this: https://alpaca.markets/docs/api-documentation/api-v2/market-data/streaming/

I don't have a live trading account. I'm essentially just trying to do paper trading and i was hoping i could websocket the quotes for a trade or two using the Alpaca Data API. I cannot use polygon services.

**Comment by mainstringargs** [comment]
Ah.  that is brand new from Alpaca, so we have yet to implement it.

**Comment by Petersoj** [comment]
I’ll be done with that PR this weekend hopefully. For now, using the Polygon API is the same thing, since the Alpaca Data Streaming API is just relaying the data from Polygon Feed.

**Comment by louisphilippe2** [comment]
From what i gathered in your code, you could make another listen/unlisten enum for the stream message types and let us add the stock symbols from there. If i understand correctly, the websocket should be able to handle it.

**Comment by Petersoj** [comment]
PR is taking me a little longer than I thought. I only have weekends to work on it.

**Comment by louisphilippe2** [comment]
Hello Petersoj, do you have an update on the project? Thank you!

**Comment by Petersoj** [comment]
@louisphilippe2 See my comment on the other PR about this issue [here](https://github.com/mainstringargs/alpaca-java/issues/64#issuecomment-640275398). I started working on this PR, but then my summer job started to take priority. Feel free to contribute via the instructions in the aforementioned link.

**Comment by Petersoj** [comment]
The WIP PR for this is now available [here.](https://github.com/Petersoj/alpaca-java/pull/71) Should be done soon.

**Comment by Petersoj** [comment]
#71 is now completed and will be integrated sometime this week which adds functionality for the new market data API.
