### ISSUE TITLE
alpaca market-data streaming support

### ISSUE THREAD

**Issue by ushulau** [Petersoj/alpaca-java#64]
As far as I can see you can not use this API to subscribe for https://alpaca.markets/docs/api-documentation/api-v2/market-data/streaming/. Is there any effort to provide support for market data endpoints?

**Comment by Petersoj** [comment]
Yeah, there is a branch on my fork with the initial stages of adding that API [here](https://github.com/Petersoj/alpaca-java/tree/new_market_data_api). You can contribute if you'd like by pulling that branch and opening a PR on my fork if you'd like. 
I would recommend just using Polygon right now as the Alpaca Data API is simply relaying data from Polygon or IEX.

**Comment by StevenMassaro** [comment]
@Petersoj Just curious, what's the status of the work on your fork? What work is still needed?

**Comment by Petersoj** [comment]
@StevenMassaro Yeah my summer job (which is currently taking up all my time) ends in 3 weeks. After that, I'll be able to pick this back up. All that's left is the websocket functionality which is practically the same as Polygon's.

**Comment by Petersoj** [comment]
The WIP PR for this is now available [here.](https://github.com/Petersoj/alpaca-java/pull/71) Should be done soon.

**Comment by jessethouin** [comment]
This is incredible work, thank you. If there's anything else left to be done that you don't have time for, please let me know. I have piqued the interest of a few Google engineers who do this as a hobby (as do I), so I'm sure we could drum up some time if necessary.

**Comment by Petersoj** [comment]
@jessethouin Hey thanks I appreciate that! As for that PR, there isn't much left to be done except for just finishing the websocket functionality (which is basically just copied from the Polygon websocket functionality). I've been swamped with school, but I should be able to finish it soon. As far as contribution, I would love help with Code Coverage and Unit Testing! More info on that [here](https://github.com/Petersoj/alpaca-java/issues/31).

**Comment by Petersoj** [comment]
#71 is now completed and will be integrated sometime this week which adds functionality for the new market data API.
