### ISSUE TITLE
Trailing stop orders

### ISSUE THREAD

**Issue by codeaches** [Petersoj/alpaca-java#73]
@Petersoj just checking to see trailing stop order service will be added in the near future?

**Comment by Petersoj** [comment]
That functionality is already in the snapshot branch. I just have to test it and then will merge and release either tomorrow or Wednesday.

**Comment by Petersoj** [comment]
This has been integrated in to version `5.2`.

**Comment by codeaches** [comment]
Thank you @Petersoj
