### ISSUE TITLE
getDailyOpenClose returning null

### ISSUE THREAD

**Issue by tamuseanmiller** [Petersoj/alpaca-java#80]
The method getDailyOpenClose in PolygonAPI seems to always return null, I didn't spend too much time on it but I couldn't tell why it was happening. I haven't tested in any environment but my own but thought I would bring it up in case others get the issue.

Just an example call...
`polygonAPI.getDailyOpenClose("AMD", lastOpenDate);`

**Comment by Petersoj** [comment]
Thanks for reporting this! I’ll investigate next week 👍

**Comment by Petersoj** [comment]
Fixed in d3ee31258a4303faf36afd965cdd948e99c0c02a. The JSON response format changed.

**Comment by Petersoj** [comment]
I will publish this in the next release once I get unit testing going 👍
