### ISSUE TITLE
If the checksums are different, please create a new issue!

### ISSUE THREAD

**Issue by belarusrulez** [Petersoj/alpaca-java#81]
![image](https://user-images.githubusercontent.com/1071191/101067061-ec682680-354b-11eb-9e11-413198f72c0c.png)
Creating ticket because "If the checksums are different, please create a new issue!" :)

**Comment by Petersoj** [comment]
This will happen if you build with a Java version other than Java 8 (JDK 1.8.0). The compiler will optimize your build differently than the Jar that I build on my machine and upload to Maven central. I'll add a note to the README. Thanks for reporting!
![alpaca-java md5](https://user-images.githubusercontent.com/14127217/101069682-90a39a80-3557-11eb-98e9-331b8f75dcf3.png)

**Comment by belarusrulez** [comment]
thx for fast respond

**Comment by belarusrulez** [comment]
as an idea. Will it make sense to put latest checksum in general readme file? that's how ppl will be able to check checksum without having to install JDK 1.8.0

**Comment by Petersoj** [comment]
Yes I can add that. A neat tool I found for Java version management is called [Jabba](https://github.com/shyiko/jabba). You can easily manage installed versions of various JDKs and switch between them seamlessly.

**Comment by belarusrulez** [comment]
@Petersoj 
Sorry to open this again. Just don't want to spawn more tickets + it's the same topic.

Could you consider something like this:
https://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github
As an example of one possible solutions from stack-overflow topic:
https://github.com/polygon-io/client-jvm

Sorry to bother you.

**Comment by Petersoj** [comment]
Using Maven Central is the standardized way of hosting Maven artifacts. Why do you want me to host the artifacts on a Github branch? Are you having issues with [Maven Central](https://search.maven.org/) and/or [Sonatype](https://oss.sonatype.org/)?
