### ISSUE TITLE
MD5 checksum Java 1.8.0_261

### ISSUE THREAD

**Issue by henning-oden** [Petersoj/alpaca-java#84]
I downloaded the Alpaca Java API for use in a programming project today and I have gotten an MD5 checksum that differs from the expected one.

Used Gradle version was 6.6.1 in Git Bash on Windows 10, Version 10.0.19041 Build 19041. 

Java: java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

MD5 using CertUtil: CertUtil -hashfile alpaca-java-6.0.1.jar md5
MD5 hash of alpaca-java-6.0.1.jar:
96d5a061107f91ab0fbf046e23edeff7
CertUtil: -hashfile command completed successfully.

The program I am building will only use the API to query stock data without making any trades. Can I safely proceed or should I try another Java version to get a matching MD5 checksum?

**Comment by Petersoj** [comment]
You can safely proceed. I added that section to the README to give users a better sense of security when using the artifacts I upload to Maven central, but I guess the MD5 checksums will still differ using the same JDK version, but with different build versions... I am using build 1.8.0_241-b07.
I will figure out a better way users can consistently verify "Maven Central Integrity."

**Comment by henning-oden** [comment]
Okay, I think I understand. Thank you!
