### ISSUE TITLE
Hello. I added sort and limit into polygon aggregations call. Can't push.

### ISSUE THREAD

**Issue by belarusrulez** [Petersoj/alpaca-java#85]
Hello. I added sort and limit into polygon aggregations call. Can't push.
![image](https://user-images.githubusercontent.com/1071191/106213362-5d5d4080-6181-11eb-8988-4f6e5c239840.png)

**Comment by Petersoj** [comment]
If you want to integrate your code into this repository, you need to create a Pull Request (PR). See [here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) for more details.

**Comment by belarusrulez** [comment]
@Petersoj thx.
