### ISSUE TITLE
Fix bars timeframe for v2

### ISSUE THREAD

**Issue by balajikandavel** [Petersoj/alpaca-java#88]
https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/#bars
There is a change in Timeframe for the aggregation. Available values are: 1Sec, 1Min, 1Hour, 1Day.

**Comment by Petersoj** [comment]
I'll update that this weekend. Thanks for reporting this.

**Comment by balajikandavel** [comment]
Thanks

**Comment by Petersoj** [comment]
@balajikandavel looks like available values are actually: 1Min, 1Hour, 1Day by the way.

**Comment by balajikandavel** [comment]
Right, looks like the document got updated now.

**Comment by Petersoj** [comment]
Fixed in [7.0](https://github.com/Petersoj/alpaca-java/releases/tag/7.0)
