### ISSUE TITLE
live configuration does not seem to be working with version 8.0.1

### ISSUE THREAD

**Issue by fear025** [Petersoj/alpaca-java#98]
When using the configuration with the parameter:
endpoint_api_type=live

The following error message is generated:
net.jacobpeterson.alpaca.rest.AlpacaClientException: java.net.UnknownHostException: No such host is known (live.alpaca.markets)

I believe this is being caused by line 134 of main/java/net/jacobpeterson/alpaca/AlpacaAPI.java
brokerHostSubdomain = "live";

This should probably be:
brokerHostSubdomain = "api";

Thank you for all of your effort in this project!

**Comment by Petersoj** [comment]
Oh whoops! I'll fix that right away. Thank you!

**Comment by Petersoj** [comment]
Fixed in [`8.0.2`](https://github.com/Petersoj/alpaca-java/releases/tag/8.0.2).
